version: '3'
services:

  # from: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es_${PROJECT_NAME}_01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/${PROJECT_NAME}/es01:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT}:9200"
    networks:
      - ${PROJECT_NAME}


  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es_${PROJECT_NAME}_02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/${PROJECT_NAME}/es02:/usr/share/elasticsearch/data
    networks:
      - ${PROJECT_NAME}


  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es_${PROJECT_NAME}_03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/${PROJECT_NAME}/es03:/usr/share/elasticsearch/data
    networks:
      - ${PROJECT_NAME}

  # from: https://www.elastic.co/guide/en/kibana/current/docker.html
  # WARNING WARNING WARNING: on mac it might be necessary to increase docker memory limit:
  # https://github.com/elastic/elasticsearch/issues/25067#issuecomment-308541732
  # more about memory limit: https://hub.docker.com/editions/community/docker-ce-desktop-mac
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: es_${PROJECT_NAME}_kibana
    environment:
      SERVER_NAME: kibana.docker
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      - es01
      - es02
      - es03
    networks:
      - ${PROJECT_NAME}

networks:
  ${PROJECT_NAME}:
    name: ${PROJECT_NAME}
    driver: bridge